package com.bancoazteca.elite.ejb.pagoServicios;

import javax.ejb.EJBLocalObject;

import com.bancoazteca.elite.beans.BeneficiarioDineroExpressRequestTO;
import com.bancoazteca.elite.beans.BeneficiarioDineroExpressResponseTO;
import com.bancoazteca.elite.beans.DonativosRequestTO;
import com.bancoazteca.elite.beans.DonativosResponseTO;
import com.bancoazteca.elite.beans.EnvioDineroExpressRequestTO;
import com.bancoazteca.elite.beans.EnvioDineroExpressResponseTO;
import com.bancoazteca.elite.beans.FrecuentesRequestTO;
import com.bancoazteca.elite.beans.FrecuentesResponseTO;
import com.bancoazteca.elite.beans.FrecuentesTiempoAireRequestTO;
import com.bancoazteca.elite.beans.FrecuentesTiempoAireResponseTO;
import com.bancoazteca.elite.beans.PagoServicioAztecaWebRequestTO;
import com.bancoazteca.elite.beans.PagoServicioAztecaWebResponseTO;
import com.bancoazteca.elite.beans.PagoServicioLuzRequestTO;
import com.bancoazteca.elite.beans.PagoServicioLuzResponsetTO;
import com.bancoazteca.elite.beans.PagoServiciosAvicolaRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosAvicolaResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosIusacellRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosIusacellResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosMaxiGasRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosMaxiGasResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosMovistarRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosMovistarResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosParametrizableRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosParametrizableResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosSkyRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosSkyResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosTelmexRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosTelmexResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosTiempoAireRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosTiempoAireResponseTO;
import com.bancoazteca.elite.beans.PagoServiciosToditoCardRequestTO;
import com.bancoazteca.elite.beans.PagoServiciosToditoCardResponseTO;
import com.bancoazteca.elite.beans.PagoTarjetaCreditoRequestTO;
import com.bancoazteca.elite.beans.PagoTarjetaCreditoResponseTO;
import com.bancoazteca.elite.beans.PagoTarjetaOtrosBancosRequestTO;
import com.bancoazteca.elite.beans.PagoTarjetaOtrosBancosResponseTO;
import com.bancoazteca.elite.ejb.exception.EliteDataException;
import com.bancoazteca.elite.ejb.exception.SessionExpiredException;
import com.bancoazteca.elite.beans.FrecuentesAztecaRequestTO;
import com.bancoazteca.elite.beans.FrecuentesAztecaResponseTO;
import com.bancoazteca.elite.beans.PagoTarjetaAztecaRequestTO;
import com.bancoazteca.elite.beans.PagoTarjetaAztecaResponseTO;

public interface PagoServiciosSL extends EJBLocalObject{
	
	public PagoServiciosTelmexResponseTO setInitialTelmexPayment(PagoServiciosTelmexRequestTO pagoServiciosTelmexRequestTO) throws PagoServiciosException, SessionExpiredException,EliteDataException; 		
	public PagoServiciosTelmexResponseTO setDataTelmexPayment(PagoServiciosTelmexRequestTO pagoServiciosTelmexRequestTO) throws PagoServiciosException, SessionExpiredException,EliteDataException;	
	public PagoServiciosTelmexResponseTO setConfimTelmexPayment(PagoServiciosTelmexRequestTO pagoServiciosTelmexRequestTO) throws PagoServiciosException, SessionExpiredException,EliteDataException;
	public FrecuentesResponseTO setEliminarFrecuentesEjecucionParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO setEliminarFrecuentesValidacionParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO setModificarFrecuentesParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO setModificarFrecuentesValidacionParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO setModificarFrecuentesEjecucionParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	
	public PagoServiciosIusacellResponseTO setInitialIusacellPayment (PagoServiciosIusacellRequestTO requestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosIusacellResponseTO setDataIusacellPayment (PagoServiciosIusacellRequestTO requestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosIusacellResponseTO setConfirmIusacellPayment (PagoServiciosIusacellRequestTO requestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public PagoServicioLuzResponsetTO setInitialLuzPayment(PagoServicioLuzRequestTO pagoServicioLuzRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServicioLuzResponsetTO setDataLuzPayment(PagoServicioLuzRequestTO pagoServicioLuzRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServicioLuzResponsetTO setConfirmLuzPayment(PagoServicioLuzRequestTO pagoServicioLuzRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public void setEndLuzPayment(PagoServicioLuzRequestTO pagoServicioLuzRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;

	public PagoServiciosSkyResponseTO setInitialSkyPayment(PagoServiciosSkyRequestTO skyRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosSkyResponseTO setDataSkyPayment(PagoServiciosSkyRequestTO skyRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosSkyResponseTO setConfirmSkyPayment(PagoServiciosSkyRequestTO skyRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public PagoServiciosMovistarResponseTO setInitialMovistarPayment(PagoServiciosMovistarRequestTO movistarRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosMovistarResponseTO setDataMovistarPayment(PagoServiciosMovistarRequestTO movistarRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosMovistarResponseTO setConfirmMovistarPayment(PagoServiciosMovistarRequestTO movistarRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public PagoServiciosTiempoAireResponseTO setMenuTiempoAirePayment(PagoServiciosTiempoAireRequestTO tiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosTiempoAireResponseTO setInitialTiempoAirePayment(PagoServiciosTiempoAireRequestTO tiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosTiempoAireResponseTO setDataTiempoAirePayment(PagoServiciosTiempoAireRequestTO tiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosTiempoAireResponseTO setConfirmTiempoAirePayment(PagoServiciosTiempoAireRequestTO tiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;

	public FrecuentesResponseTO setInitialFrecuentesParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO setAgregarFrecuenteParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO setAgregarFrecuenteEjecucionParametrizado(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;

	public PagoTarjetaCreditoResponseTO setInitialTarjetaCreditoPayment(PagoTarjetaCreditoRequestTO pagoTarjetaCreditoRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoTarjetaCreditoResponseTO setDataTarjetaCreditoPayment(PagoTarjetaCreditoRequestTO pagoTarjetaCreditoRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoTarjetaCreditoResponseTO setConfirmTarjetaCreditoPayment(PagoTarjetaCreditoRequestTO pagoTarjetaCreditoRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;

	public PagoTarjetaOtrosBancosResponseTO getInitialTarjetaPaymentOthersBank(PagoTarjetaOtrosBancosRequestTO tarjetaOtrosBancosRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoTarjetaOtrosBancosResponseTO getDataTarjetaPaymentOthersBank(PagoTarjetaOtrosBancosRequestTO tarjetaOtrosBancosRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoTarjetaOtrosBancosResponseTO getConfirmTarjetaPaymentOthersBank(PagoTarjetaOtrosBancosRequestTO tarjetaOtrosBancosRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public String setSendMailTarjetaPaymentOthersBank(PagoTarjetaOtrosBancosRequestTO tarjetaOtrosBancosRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;	

	public FrecuentesResponseTO setConsultaCuentasFrecuentesTarjetasOtrosBancos(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO setAgregaCuentasFrecuentesTarjetasOtrosBancos(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesResponseTO iniciarEditarEliminarCuentasFrecuentesTarjetasOtrosBancos (FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;		
	public FrecuentesResponseTO ejecutarEditarEliminarCuentasFrecuentesTarjetasOtrosBancos (FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;	
	public FrecuentesResponseTO setConsultaCuentasFrecuentesTiempoAire(FrecuentesRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	//nuevo referencias frecuentes tiempo aire
	public FrecuentesTiempoAireResponseTO referenciasFrecuentesTiempoAireInit(FrecuentesTiempoAireRequestTO frecuentesTiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesTiempoAireResponseTO setAgregaReferenciasFrecuentesTiempoAire(FrecuentesTiempoAireRequestTO frecuentesTiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesTiempoAireResponseTO setBorraReferenciasFrecuentesTiempoAireValidacion(FrecuentesTiempoAireRequestTO frecuentesTiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesTiempoAireResponseTO setBorraReferenciasFrecuentesTiempoAireEjecucion(FrecuentesTiempoAireRequestTO frecuentesTiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesTiempoAireResponseTO setModificaReferenciasFrecuentesTiempoAireValidacion(FrecuentesTiempoAireRequestTO frecuentesTiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesTiempoAireResponseTO setModificaReferenciasFrecuentesTiempoAireEjecucion(FrecuentesTiempoAireRequestTO frecuentesTiempoAireRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	//nuevo referencias frecuentes tiempo aire
	
	public PagoServiciosMaxiGasResponseTO setInitialMaxiGasPayment(PagoServiciosMaxiGasRequestTO pagoServiciosMaxiGasRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosMaxiGasResponseTO setDataMaxiGasPayment(PagoServiciosMaxiGasRequestTO pagoServiciosMaxiGasRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosMaxiGasResponseTO setConfimMaxiGasPayment(PagoServiciosMaxiGasRequestTO pagoServiciosMaxiGasRequestTO) throws PagoServiciosException, SessionExpiredException,EliteDataException;
	
	public PagoServicioAztecaWebResponseTO setInitialAztecaWebPayment(PagoServicioAztecaWebRequestTO pagoServicioAztecaWebRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException ;
	public PagoServicioAztecaWebResponseTO setDataAztecaWebPayment(PagoServicioAztecaWebRequestTO pagoServicioAztecaWebRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException ;
	public PagoServicioAztecaWebResponseTO setConfimAztecaWebPayment(PagoServicioAztecaWebRequestTO pagoServicioAztecaWebRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException ;
	
	public PagoServiciosAvicolaResponseTO setInitialAvicolaPayment(PagoServiciosAvicolaRequestTO pagoServiciosAvicolaRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosAvicolaResponseTO setDataAvicolaPayment(PagoServiciosAvicolaRequestTO pagoServiciosAvicolaRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosAvicolaResponseTO setConfirmAvicolaPayment(PagoServiciosAvicolaRequestTO pagoServiciosAvicolaRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public DonativosResponseTO setInitialDonativo(DonativosRequestTO donativosRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public DonativosResponseTO setDataDonativo(DonativosRequestTO donativosRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public DonativosResponseTO setConfirmDonativo(DonativosRequestTO donativosRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public BeneficiarioDineroExpressResponseTO setDataEnvioDineroExpressAltaFrecuente(BeneficiarioDineroExpressRequestTO frecuenteRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public BeneficiarioDineroExpressResponseTO setEnvioDineroExpressAltaFrecuenteEjecutar(BeneficiarioDineroExpressRequestTO frecuenteRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;

	public BeneficiarioDineroExpressResponseTO setEnvioDineroExpressConsultarFrecuentesEjecutar(BeneficiarioDineroExpressRequestTO frecuenteRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public EnvioDineroExpressResponseTO setEnvioDineroExpressInicio(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public EnvioDineroExpressResponseTO setEnvioDineroExpressValidacion(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public EnvioDineroExpressResponseTO setEnvioDineroExpressEjecucion(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public EnvioDineroExpressResponseTO setEnvioDineroExpressEstados(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public EnvioDineroExpressResponseTO setEnvioDineroExpressCiudades(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public EnvioDineroExpressResponseTO setEnvioDineroExpressAgentes(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public EnvioDineroExpressResponseTO setEnvioDineroExpressSucursales(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;	
	public EnvioDineroExpressResponseTO enviaCorreoConfirmacionDineroExpress(EnvioDineroExpressRequestTO requestTO)throws SessionExpiredException,EliteDataException,PagoServiciosException;

	
	public EnvioDineroExpressResponseTO setEnvioDineroExpressCalculoComision(EnvioDineroExpressRequestTO dineroExpressRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public PagoServiciosParametrizableResponseTO setInitialParametrizablePayment(PagoServiciosParametrizableRequestTO parametrizableRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosParametrizableResponseTO setDataParametrizablePayment(PagoServiciosParametrizableRequestTO parametrizableRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoServiciosParametrizableResponseTO setConfirmParametrizablePayment(PagoServiciosParametrizableRequestTO parametrizableRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	public PagoServiciosToditoCardResponseTO getInitialToditoCard(PagoServiciosToditoCardRequestTO toditoCardRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
//Pago de Tarjeta Azteca
	
	
	public PagoTarjetaAztecaResponseTO solicitudPagoTarjetaAzteca(PagoTarjetaAztecaRequestTO pagoTarjetaAztecaRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoTarjetaAztecaResponseTO validacionPagoTarjetaAzteca(PagoTarjetaAztecaRequestTO pagoTarjetaAztecaRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public PagoTarjetaAztecaResponseTO confirmacionPagoTarjetaAzteca(PagoTarjetaAztecaRequestTO pagoTarjetaAztecaRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;

	//Envio de email pago de tarjeta Azteca
	public PagoTarjetaAztecaResponseTO envioMail(PagoTarjetaAztecaRequestTO pagoTarjetaAztecaRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	
	
	//Alta y edición de cuentas frecuentes
	public FrecuentesAztecaResponseTO AgregaCuentasFrecuentesTarjetasAzteca(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;
	public FrecuentesAztecaResponseTO iniciarEditarCuentasFrecuentesTarjetasAzteca(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;		
	public FrecuentesAztecaResponseTO ejecutarEditarCuentasFrecuentesTarjetasAzteca(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;	
	
	
	//Eliminacion de tarjetas frecuentes
	
	public FrecuentesAztecaResponseTO iniciarEliminarCuentasFrecuentesTarjetasAzteca(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;		
	public FrecuentesAztecaResponseTO ejecutarEliminarCuentasFrecuentesTarjetasAzteca(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;	
	
	
	//Consulta de Tarjetas Azteca Frecuentes
	public FrecuentesAztecaResponseTO consultaCuentasFrecuentesTarjetasAzteca(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;

	
	//Validacion de Alta y Edicion de tarjetas frecuentes
	
	public FrecuentesAztecaResponseTO validarAltaCuentasFrecuentes(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;		
	public FrecuentesAztecaResponseTO validarEdicionCuentasFrecuentes(FrecuentesAztecaRequestTO frecuentesRequestTO) throws PagoServiciosException, SessionExpiredException, EliteDataException;	
	
}
