package com.bancoazteca.eservice.command.base;

public interface CommandConstantes {
	String INVALIDATE_IDSESSION ="idSession";
	String INVALIDATE_IDAPPLICATION = "idApplication";
	String INVALIDATE_IDAPPLICATION_IDSESSION = "idApplication_idSession";
	String ID_APPLICATION_EXPIRADA = "idApplicationExpirada";
	String ID_APPLICATION_INCORRECTA = "idApplicationIncorrecta";
	String ID_APPLICATION_VALIDA = "idApplicationValida";
	String GENERATE_ID_APPLICATION = "idApplication";
	String GENERATE_ID_SESSION ="idSession";
	String PAGO_SERVICIO = "pago.servicio.";
	String VARIABLE_FILTRO_DE_CUENTAS = "user.proxyelite.user.";
	String PAGO_SERVICIO_REFERENCIA = "pago.servicio.referencia.longitud.";
	String PAGO_SERVICIO_REFERENCIA_UNO = "pago.servicio.referencia.longitud.uno.";
	String PAGO_SERVICIO_REFERENCIA_DOS = "pago.servicio.referencia.longitud.dos.";
	String PAGO_SERVICIO_PARAMETRIZABLE =  "PagoServicioParametrizable.properties";
	String FILTRADO_CUENTAS =  "eServiceUsers.properties";
	String FECHA_SOLICITUD = "fecha_solicitud";
	String NUMERO_CUENTA = "numero_cuenta";
	String NOMBRE_USUARIO="nombreUsuario";
	
	String OPERACIONES_TOKEN_TO = "CommandConstantes.OPERACIONES_TOKEN_TO";
	String BLOQUEO_FIRMA_TO = "CommandConstantes.BLOQUEO_FIRMA_REQUEST_TO";
	String LISTA_TOKEN = "CommandConstantes.LISTA_TOKEN_TO";
	String CONFIRMACION_NUMERO_SERIE = "CommandConstantes.CONFIRMACION_NUMERO_SERIE";
	String LISTA_COMPANIAS = "CommandConstantes.LISTA_COMPANIAS";
	String LISTA_CUENTAS = "CommandConstantes.LISTA_CUENTAS";
	
	String CLIENTE_TO = "CommandConstantes.CLIENTE_TO";
	
	String B402_ACTUALIZACION_SALDO_CUENTA = "CommandConstantes.B402_ACTUALIZACION_SALDO_CUENTA";
	
	String ESTATUS_CUENTAS_TO = "CommandConstantes.ESTATUS_CUENTA_TO";
	String RESUMEN_MOVIMIENTOS_CUENTAS = "CommandConstantes.RESUMEN_MOVIMIENTOS_CUENTAS";
	String TRASPASOS_PROPIAS_VALIDATE_RESPONSE = "CommandConstantes.TRASPASOS_PROPIAS_VALIDATE_RESPONSE";
	String TRASPASOS_PROPIAS_RESPONSE = "CommandConstantes.TRASPASOS_PROPIAS_RESPONSE";
	String TRANSFERENCIA_SPEI_RESPONSE="CommandConstantes.TRANSFERENCIA_SPEI_RESPONSE";
	String TRANSFERENCIA_TEF_RESPONSE="CommandConstantes.TRANSFERENCIA_TEF_RESPONSE";
	String TRANSFERENCIA_TERCEROS_RESPONSE="CommandConstantes.TRANSFERENCIA_TERCEROS_RESPONSE";
	String PAGOSERVICIOS_TELMEX_RESPONSE="CommandConstantes.PAGOSERVICIOS_TELMEX_RESPONSE";
	String PAGOSERVICIOS_TELMEX_SOLICITUD_RESPONSE="CommandConstantes.PAGOSERVICIOS_TELMEX_SOLICITUD_RESPONSE";
	String PAGOSERVICIOS_TELMEX_VALIDACION_RESPONSE="CommandConstantes.PAGOSERVICIOS_TELMEX_VALIDACION_RESPONSE";
	String CUENTA_SOCIO_RESPONSE="CommandConstantes.CUENTA_SOCIO_RESPONSE";
	//Constantes transferencias internacionales
	String TRANSFERENCIA_INTERNACIONAL_RESPONSE = "CommandConstantes.TRANSFERENCIA_INTERNACIONAL_RESPONSE";
	
	//Constantes Pago de servicios MaxiGas
	String PAGO_SERVICIO_MAXIGAS_RESPONSE="CommandConstantes.PAGO_SERVICIO_MAXIGAS_RESPONSE";
	
	String DISPOSITIVO_HUELLA = "CommandConstantes.DISPOSITIVO_HUELLA";
	
	String PAISES_TO = "CommandConstantes.PAISES_TO";
	String CIUDADES_TO = "CommandConstantes.CIUDADES_TO";
	String SWIFT_ABA_TO = "CommandConstantes.SWIFT_ABASTO";
	String PAGO_SERVICIO_SKY_RESPONSE = "CommandConstantes.PAGO_SERVICIO_SKY_RESPONSE";
	String TIEMPO_AIRE_TO = "CommandConstantes.TIEMPO_AIRETO";
	String PAGO_SERVICIO_IUSACELL_RESPONSE = "CommandConstantes.PAGO_SERVICIO_IUSACELL_RESPONSE";
	String PAGO_SERVICIO_IUSACELL_SOLICITUD_RESPONSE = "CommandConstantes.PAGO_SERVICIO_IUSACELL_SOLICITUD_RESPONSE";
	
	String PAGO_SERVICIO_TIEMPO_AIRE_FRECUENTES_RESPONSE="CommandConstantes.PAGO_SERVICIO_TIEMPO_AIRE_FRECUENTES_RESPONSE";;
	String PAGO_SERVICIOS_MOVISTAR_RESPONSE = "CommandConstantes.PAGO_SERVICIOS_MOVISTAR_RESPONSE";
	String PAGO_SERVICIOS_LUZ_RESPONSE = "CommandConstantes.PAGO_SERVICIOS_LUZ_RESPONSE";
	String PAGO_SERVICIOS_LUZ_REQUEST = "CommandConstantes.PAGO_SERVICIOS_LUZ_REQUEST";
	String PAGO_SERVICIOS_PARAMETRIZABLE_RESPONSE = "CommandConstantes.PAGO_SERVICIOS_PARAMETRIZABLE_RESPONSE";

	String FRECUENTES_TRASPASOS_TERCEROS_RESPONSE = "CommandConstantes.FRECUENTES_TRASPASOS_TERCEROS_RESPONSE";
	//Constantes para pago de tarjetas de crédito otros bancos
	String PAGO_SERVICIO_TARJETA_OTROS_BANCOS_RESPONSE = "CommandConstantes.PAGO_SERVICIO_TARJETA_OTROS_BANCOS_RESPONSE";
	String CONSULTA_FRECUENTES_PAGO_TARJETA_OTROS_BANCOS_RESPONSE = "CommandConstantes.CONSULTA_FRECUENTES_PAGO_TARJETA_OTROS_BANCOS_RESPONSE";
	String FRECUENTES_PAGO_TARJETA_OTROS_BANCOS_REQUEST = "CommandConstantes.FRECUENTES_PAGO_TARJETA_OTROS_BANCOS_REQUEST";
	

	//Constantes de Estado de Cuenta
	String ESTADO_CUENTA_RESPONSE = "CommandConstantes.ESTADO_CUENTA_RESPONSE";
	String TIPO_ESTADO_CUENTA = "CommandConstantes.TIPO_ESTADO_CUENTA";
	String PRODUCTO_SOCIO_PLUS="97";
	String FLAG_SOCIO_PLUS_VALIDATION_NEXT_METHOD="CommandConstantes.FLAG_SOCIO_PLUS_VALIDATION";
	String CUENTAS_INDEX="CommandConstantes.CUENTAS_INDEX";

	//Constantes para otros bancos Frecuentes
	String CUENTAS_FRECUENTES_RESPONSE = "CommandConstantes.CUENTAS_FRECUENTES_RESPONSE";
	String CUENTAS_FRECUENTES_REQUEST = "CommandConstantes.CUENTAS_FRECUENTES_REQUEST";
	String CUENTAS_FRECUENTES_TEF_SPEI ="CommandConstantes.CUENTAS_FRECUENTES_TEF_SPEI";
	String CUENTAS_FRECUENTES_LIST = "CommandConstantes.CUENTAS_FRECUENTES_LIST";
	String CUENTAS_FRECUENTES_TERCEROS ="CommandConstantes.CUENTAS_FRECUENTES_TERCEROS";
	String CUENTAS_FRECUENTES_INTERNACIONALES = "CommandConstantes.CUENTAS_FRECUENTES_INTERNACIONALES";
	String PAGO_SERVICIO_AZTECAWEB_RESPONSE = "CommandConstantes.PAGO_SERVICIO_AZTECAWEB_RESPONSE";
	//Cuenta PLata Constantes
	String CUENTA_PLATA_RESPONSE = "CommandConstantes.CUENTA_PLATA_RESPONSE";
	String COLECCION_BENEFICIARIOS_CUENTA_PLATA="CommandConstantes.COLECCION_BENEFICIARIOS_CUENTA_PLATA";
	
	//Constantes para pago avicola san andres
	String PAGO_SERVICIO_AVICOLA_RESPONSE = "CommandConstantes.PAGO_SERVICIO_AVICOLA_RESPONSE";
	/**
	 * CommandConstantes.MIS_FINANZAS_REQUEST
	 */
	String MIS_FINANZAS="CommandConstantes.MIS_FINANZAS_REQUEST";
	String CUENTAS_MISFINANZAS_TO = "CommandConstantes.CUENTAS_MISFINANZAS_TO";
	String COLLECTION_CUENTAS_MISFINANZAS_TO = "CommandConstantes.COLLECTION_CUENTAS_MISFINANZAS_TO";
	String COLLECTION_MOVIMIENTOS_MISFINANZAS_TO = "CommandConstantes.COLLECTION_MOVIMIENTOS_MISFINANZAS_TO";
	String PAGO_TARJETA_CREDITO_RESPONSE="CommandConstantes.PAGO_TARJETA_CREDITO_RESPONSE";
	String PAGO_TARJETA_CREDITO_RESPONSE_DATOS="CommandConstantes.PAGO_TARJETA_CREDITO_RESPONSE_DATOS";
	String PAGO_TARJETA_CREDITO_RESPONSE_DATOS_FORMATEADOS="CommandConstantes.PAGO_TARJETA_CREDITO_RESPONSE_DATOS_FORMATEADOS";
	String DATOS_REQUEST_MIS_FINANZAS_TO = "CommandConstantes.DATOS_REQUEST_MIS_FINANZAS_TO";
	
	String DETALLE_OTROS_CREDITOS="CommandConstantes.DETALLE_OTROS_CREDITOS";
	//Constantes CuentaMercadoDinero
	String PLAZO_TAZA_COLLECTION="CommandConstantes.PLAZO_TAZA_COLLECTION";
	String INVERSION_REPORTOS_CUENTAS="CommandConstantes.INVERSION_REPORTOS_CUENTAS";
	String INVERSION_REPORTOS_MONTO_MINIMO="CommandConstantes.INVERSION_REPORTOS_MONTO_MINIMO";
	String ERROR_SALDO_MONTO="CommandConstantes.ERROR_SALDO_MONTO";
	String ACTION_ERRORS="CommandConstantes.ACTION_ERRORS";
	String EJECUTAR_APERTURA="CommandConstantes.PLAZO_TAZA_COLLECTION";
	String INVERSION_RESUMEN_OPERACIONES_VIGENTES="CommandConstantes.PLAZO_TAZA_COLLECTION";
	String INVERSION_RESUMEN_OPERACIONES_HISTORICAS="CommandConstantes.PLAZO_TAZA_COLLECTION";
	String INVERSION_ERRORES="CommandConstantes.INVERSION_ERRORES";
	//Cuenta Eje elite
	String APERTURA_EJE_ELITE = "CommandConstantes.APERTURA_EJE_ELITE";
	//Cuenta socio plus
	String APERTURA_SOCIO_PLUS="CommandConstantes.APERTURA_SOCIO_PLUS";
	String SOCIO_PLUS_RESPONSE="CommandConstantes.SOCIO_PLUS_RESPONSE";
	//Niveles seguridad
	String NIVELES_SEGURIDAD="CommandConstantes.NIVELES_SEGURIDAD";
	String MEDIOS_PAGO_TARJETAS = "CommandConstantes.MEDIOS_PAGO_TARJETAS";
	String MEDIOS_PAGO_DETALLE = "CommandConstantes.MEDIOS_PAGO_DETALLE";
	String MEDIOS_PAGO = "CommandConstantes.MEDIOS_PAGO";
	String LOCKUNLOCKRESPONSETO = "CommandConstantes.LOCKUNLOCKRESPONSETO";
	String CANCELACIONELEMENT_TO = "CommandConstantes.CANCELACIONELEMENT_TO";
	
	String CAMBIO_NIP_REQUEST="CommandConstantes.CAMBIO_NIP_REQUEST";
	//Donativos
	String DONATIVOS_CUENTA_RESPONSE = "CommandConstantes.DONATIVOS_CUENTA_RESPONSE";
	String DONATIVOS_RESPONSE = "CommandConstantes.DONATIVOS_RESPONSE";
	String DONATIVOS_CLIENTE = "CommandConstantes.DONATIVOS_CLIENTE";
	//Detalle Donativos
	String DETALLE_DONATIVOS = "CommandConstantes.DETALLE_DONATIVOS";
	//Dinero Express Beneficiario
	String DINERO_EXPRESS_FRECUENTE_RESPONSE = "CommandConstantes.DINERO_EXPRESS_FRECUENTE_RESPONSE";

	//Cuenta plata
	String CUENTA_PLATA_PROPS = "CuentaPlataFiltro.properties";
	String CUENTA_PLATA_PRODUCTO = "cuenta.eje.plata.producto";
	String CUENTA_PLATA_SUBPRODUCTO = "cuenta.eje.plata.subproducto";
	String SOLICITUD_DISPOSITIVO_DATOS_CUENTA="CommandConstantes.SOLICITUD_DISPOSITIVO_DATOS_CUENTA";
	String SOLICITUD_DISPOSITIVO_CUENTAS="CommandConstantes.SOLICITUD_DISPOSITIVO_CUENTAS";
	
	//Solicitud Dispositivos
	String LISTA_ESTADOS_DISPOSITIVO = "CommandConstantes.LISTA_ESTADOS_DISPOSITIVOS";
	
	//CHEQUERAS
	String CHEQUERA_ACTIVACION_RESPONSE = "CommandConstantes.CHEQUERA_ACTIVACION_RESPONSE";
	String CHEQUERA_LIBERACION_RESPONSE = "CommandConstantes.CHEQUERA_LIBERACION_RESPONSE";
	String CANCELACION_CHEQUES_CUENTA_CARGO = "CommandConstantes.CANCELACION_CHEQUES_CUENTA_CARGO";
	String CANCELACION_CHEQUES_RESUMEN_CHEQUERA = "CommandConstantes.CANCELACION_CHEQUES_RESUMEN_CHEQUERA";
	String LISTA_ESTADOS_CHEQUES = "CommandConstantes.LISTA_ESTADOS_CHEQUES";
	String CONSULTA_CHEQUERAS_CUENTAS="CommandConstantes.CONSULTA_CHEQUERAS_CUENTAS";
	String CONSULTA_CHEQUERAS_CHEQUERAS="CommandConstantes.CONSULTA_CHEQUERAS_CHEQUERAS";
	String CONSULTA_CHEQUERAS_CUENTA="CommandConstantes.CONSULTA_CHEQUERAS_CUENTA";
	String CONSULTA_CHEQUERA_DATOS= "CommandConstantes.CONSULTA_CHEQUERA_DATOS";
	String DETALLE_ROBO_CHEQUERA="CommandConstantes.DETALLE_ROBO_CHEQUERA";
	
	//Constantes de Estado de Cuenta Mercado Dinero
	String ESTADO_CUENTA_REPORTOS = "CommandConstantes.ESTADO_CUENTA_REPORTOS";	
	
	//Constantes de Actualizar Datos
	String COMPANIAS_CELULARES_ACTUALIZAR_DATOS = "CommandConstantes.COMPANIAS_CELULARES_ACTUALIZAR_DATOS";
	String DATOS_USUARIO_ACTUALIZAR_DATOS = "CommandConstantes.DATOS_USUARIO_ACTUALIZAR_DATOS";
	
	//Constantes de referencias frecuentes en servicio de pagos parametrizados
	String REFERENCIA_FRECUENTE_SERVICIO = "CommandConstantes.REFERENCIA_FRECUENTE_SERVICIO";
	String USER_ID = "CommandConstantes.USER_ID";
	String REFERENCIA_FRECUENTE_ACTIVAR = "CommandConstantes.REFERENCIA_FRECUENTE_ACTIVAR";
	String REFERENCIA_FRECUENTE_ELIMINAR = "CommandConstantes.REFERENCIA_FRECUENTE_ELIMINAR";
	String REFERENCIA_FRECUENTE_MODIFICAR = "CommandConstantes.REFERENCIA_FRECUENTE_MODIFICAR";
	String PAGO_SERVICIO_REFERENCIA_TIPO = "pago.servicio.referencia.";

	//Constantes de alerta celular
	String ACTIVAR_SERVICIO = "Activa tu Servicio";
	String TIPO_PRODUCTO = "tipoUsuario";
	String CUENTA_SELECCIONADA = "cuentaSeleccionada";
	String COMPANIAS_TOTALES = "total";
	String COLECCION_COMPANIAS_ALERTA_CELULAR = "CommandConstantes.COLECCION_COMPANIAS_ALERTA_CELULAR";
	String CLAVE_CONFIRMACION_ALERTA_CELULAR = "CommandConstantes.CLAVE_CONFIRMACION_ALERTA_CELULAR"; 
	String FLAG_HUELLA_SESSION = "CommandConstantes.FLAG_HUELLA_SESSION";
	String DATA_REQUEST_ALERTA_CELULAR = "CommandConstantes.DATA_REQUEST_ALERTA_CELULAR";
	String ACTIVADO_ALERTA_CELULAR = "ACTIVADO";
	String DESACTIVADO_ALERTA_CELULAR = "DESACTIVADO";
	String CANTIDAD_MINIMO_DEPOSITO = "1.00";
	String CANTIDAD_MINIMO_RETIRO = "1.00";
	String DATA_DELETE_ALERTA_CELULAR = "CommandConstantes.DATA_DELETE_ALERTA_CELULAR";
	String INIT_DATA_ALERTA_CELULAR = "CommandConstantes.INIT_DATA_ALERTA_CELULAR";
	String ACTIVA_DATOS_ALERTA_CELULAR = "CommandConstantes.ACTIVA_DATOS_ALERTA_CELULAR";
	String MODIFICA_DATOS_ALERTA_CELULAR = "CommandConstantes.MODIFICA_DATOS_ALERTA_CELULAR";
	String CONFIRMACION_ELIMINACION_ALERTA_CELULAR = "Tu operación se ha realizado con éxito";

	//Cuentas de cargo
	String CUENTAS_CARGO = "CommandConstantes.CUENTAS_CARGO";
	String CUENTAS_FRECUENTES_PAGO_TARJETA_AZTECA = "CommandConstantes.CUENTAS_FRECUENTES_PAGO_TARJETA_AZTECA";
	String Index = "CommandConstantes.Index";
	
	String CONSULTA_EXPRESS_REQUEST="CommandConstantes.CONSULTA_EXPRESS_REQUEST";
	
	
	
	String COLECCION_BANCOS_ORDENADOS = "principalesBancos.properties";
	String CANTIDAD_BANCOS_A_ORDENAR = "bancos.ordenados.cantidad";
	String CLAVE_BANCOS_A_ORDENAR = "bancos.ordenados.clave";
	
	String INDICE_REFERENCIA_EDITAR = "CommandConstantes.INDICE_REFERENCIA_EDITAR";
	String INDICE_REFERENCIA_ELIMINAR = "CommandConstantes.INDICE_REFERENCIA_ELIMINAR";
	String COMPANIA_CELULAR_REFERENCIA = "CommandConstantes.COMPANIA_CELULAR_REFERENCIA";
	
	String OPERACION_FRECUENTE_EXITO = "EXITO";
	String OPERACION_FRECUENTE_EXCEDE = "EXCEDE";
	
	String FOTO_UNICA_DATOS =  "datosConexionFotoUnica.properties";
	String FOTO_UNICA_IP = "dato.conexion.pstrIP";
	String FOTO_UNICA_PORT = "dato.conexion.pstrServerPort";
}

