package com.bancoazteca.elite.ejb.transferencias;

import java.util.Collection;

import javax.ejb.EJBException;
import javax.ejb.EJBLocalObject;

import com.bancoazteca.elite.beans.ConsultaTransferenciasRequestTO;
import com.bancoazteca.elite.beans.ConsultaTransferenciasResponseTO;
import com.bancoazteca.elite.beans.CuentasTransferenciasTO;
import com.bancoazteca.elite.beans.EnvioMailRequestTO;
import com.bancoazteca.elite.beans.EnvioMailResponseTO;
import com.bancoazteca.elite.beans.InternacionalesBancosRequestTO;
import com.bancoazteca.elite.beans.InternacionalesBancosResponseTO;
import com.bancoazteca.elite.beans.LabelValueBeanTO;
import com.bancoazteca.elite.beans.SpeiProgramadoRequestTO;
import com.bancoazteca.elite.beans.TransferenciaTercerosRequestTO;
import com.bancoazteca.elite.beans.TransferenciaTercerosResponseTO;
import com.bancoazteca.elite.beans.TransferenciasInternacionalesRequestTO;
import com.bancoazteca.elite.beans.TransferenciasInternacionalesResponseTO;
import com.bancoazteca.elite.beans.TransferenciasOtrosBancosTO;
import com.bancoazteca.elite.beans.TransferenciasSpeiRequestTO;
import com.bancoazteca.elite.beans.TransferenciasSpeiResponseTO;
import com.bancoazteca.elite.beans.TransferenciasTEFRequestTO;
import com.bancoazteca.elite.beans.TransferenciasTEFResponseTO;
import com.bancoazteca.elite.ejb.cuentas.CuentasException;
import com.bancoazteca.elite.ejb.exception.EliteDataException;
import com.bancoazteca.elite.ejb.exception.SessionExpiredException;

/**
 * @author Banco Azteca S.A. [JFAV] Agosto 26, 2008.
 */
public interface TransferenciasSL extends EJBLocalObject {
	
	public TransferenciaTercerosResponseTO getTransferenciaTercerosInvocacion(TransferenciaTercerosRequestTO transferenciaTercerosRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException; 
	
	public TransferenciaTercerosResponseTO getTransferenciaTercerosEnvioDatos(TransferenciaTercerosRequestTO transferenciaTercerosRequestTO)throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public TransferenciaTercerosResponseTO getEjecutarTransferenciaTerceros(TransferenciaTercerosRequestTO transferenciaTercerosRequestTO)throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public EnvioMailResponseTO envioMailTerceros(EnvioMailRequestTO envioMailRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;

	public TransferenciasSpeiResponseTO getTransferenciaSpeiInvocacion(TransferenciasSpeiRequestTO transferenciasSpeiRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public TransferenciasSpeiResponseTO getTransferenciaSpeiEnvioDatos(TransferenciasSpeiRequestTO transferenciasSpeiRequestTO)throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public TransferenciasSpeiResponseTO getEjecutarTransferenciaSpei(TransferenciasSpeiRequestTO transferenciasSpeiRequestTO)throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public EnvioMailResponseTO envioMailSpei(EnvioMailRequestTO envioMailRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public EnvioMailResponseTO envioMailSpei30(EnvioMailRequestTO envioMailRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public TransferenciasTEFResponseTO getTransferenciaTefInvocacion(TransferenciasTEFRequestTO transferenciasTEFRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;

	public TransferenciasTEFResponseTO getTransferenciaTefEnvioDatos(TransferenciasTEFRequestTO transferenciasTEFRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;

	public TransferenciasTEFResponseTO getEjecutarTransferenciaTef(TransferenciasTEFRequestTO transferenciasTEFRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public EnvioMailResponseTO envioMailTef(EnvioMailRequestTO envioMailRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;

	public TransferenciasInternacionalesResponseTO getTransferenciaInternacionalInvocacion(TransferenciasInternacionalesRequestTO transferenciasInternacionalesRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public TransferenciasInternacionalesResponseTO getTransferenciaInternacionalEnvioDatos(TransferenciasInternacionalesRequestTO transferenciasInternacionalesRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public TransferenciasInternacionalesResponseTO getEjecutarTransferenciaInternacional (TransferenciasInternacionalesRequestTO transferenciasInternacionalesRequestTO)throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public EnvioMailResponseTO envioMailInternacional(EnvioMailRequestTO envioMailRequestTO) throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;
	
	public InternacionalesBancosResponseTO getInternacionalesPaises(InternacionalesBancosRequestTO internacionalesBancosRequestTO) throws SessionExpiredException, TransferenciasException, EliteDataException;
	
	public InternacionalesBancosResponseTO getInternacionalesCiudades(InternacionalesBancosRequestTO internacionalesBancosRequestTO) throws SessionExpiredException, TransferenciasException, EliteDataException;

	public InternacionalesBancosResponseTO getInternacionalesBancos(InternacionalesBancosRequestTO internacionalesBancosRequestTO) throws SessionExpiredException, TransferenciasException, EliteDataException;
	
	public Collection<TransferenciasOtrosBancosTO> getListadoBancosTefSpeiResponseTO(TransferenciasTEFResponseTO transferenciasTEFResponseTO,TransferenciasSpeiResponseTO transferenciasSpeiResponseTO)throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException ;
	
	public Collection<CuentasTransferenciasTO> getListadoCuentasSuggest(Collection<LabelValueBeanTO> cuentasTodas,TransferenciaTercerosResponseTO tercerosResponseTO,TransferenciasTEFResponseTO tefResponseTO,TransferenciasSpeiResponseTO speiResponseTO,TransferenciasInternacionalesResponseTO internacionalesResponseTO)throws EJBException, TransferenciasException, SessionExpiredException, EliteDataException;

	public ConsultaTransferenciasResponseTO findInitialHistoricoTransferencias(ConsultaTransferenciasRequestTO consultaTransferenciasRequestTO)throws SessionExpiredException, TransferenciasException, EliteDataException;
	
	public ConsultaTransferenciasResponseTO findDataHistoricoTransferencias(ConsultaTransferenciasRequestTO consultaTransferenciasRequestTO)throws SessionExpiredException, TransferenciasException, EliteDataException;
	
	public ConsultaTransferenciasResponseTO findInitialHistoricoTraspasos(ConsultaTransferenciasRequestTO consultaTransferenciasRequestTO)throws SessionExpiredException, TransferenciasException, EliteDataException; 
	
	public ConsultaTransferenciasResponseTO findDataHistoricoTraspasos(ConsultaTransferenciasRequestTO consultaTransferenciasRequestTO)throws SessionExpiredException, TransferenciasException, EliteDataException;
	
	public ConsultaTransferenciasResponseTO findInitialTransferenciasProgramadas(ConsultaTransferenciasRequestTO consultaTransferenciasRequestTO)throws SessionExpiredException, TransferenciasException, EliteDataException;
	
	public ConsultaTransferenciasResponseTO findDataTransferenciasProgramadas(ConsultaTransferenciasRequestTO consultaTransferenciasRequestTO)throws SessionExpiredException, TransferenciasException, EliteDataException;

	public ConsultaTransferenciasResponseTO findDetalleHistoricoTransferencias(ConsultaTransferenciasRequestTO consultaTransferenciasRequestTO)throws SessionExpiredException, TransferenciasException, EliteDataException;
	
	public TransferenciasSpeiResponseTO insertaSpei30(SpeiProgramadoRequestTO speiRequestTO) throws  CuentasException, SessionExpiredException, EliteDataException,TransferenciasException;
}
